/**
 * Android hardening that has to happen at the native level.
 *
 * Written as a config plugin rather than a hand edit of `android/`, because
 * `expo prebuild` regenerates that directory and would discard direct changes.
 *
 * What it does:
 *  - Installs a network security config that refuses cleartext HTTP outright and
 *    trusts only the system CA store, so a user-installed CA (the usual way an
 *    interception proxy is planted on a device) cannot silently read traffic.
 *  - Turns off Android auto-backup, so the app's private storage is not copied
 *    into a Google backup a user cannot inspect.
 *  - Blocks the app from being captured or embedded by other apps' overlays.
 */
const {
  AndroidConfig,
  withAndroidManifest,
  withDangerousMod,
} = require('expo/config-plugins');
const fs = require('node:fs');
const path = require('node:path');

const NETWORK_SECURITY_CONFIG = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidSecurity.js. Do not edit by hand. -->
<network-security-config>
    <!--
      cleartextTrafficPermitted="false" means every request must be HTTPS.
      Only the system CA store is trusted: a CA the user (or an attacker with
      device access) installs is ignored, which blocks casual MITM proxying.
    -->
    <base-config cleartextTrafficPermitted="false">
        <trust-anchors>
            <certificates src="system" />
        </trust-anchors>
    </base-config>
</network-security-config>
`;

/** Write res/xml/network_security_config.xml into the generated project. */
function withNetworkSecurityConfigFile(config) {
  return withDangerousMod(config, [
    'android',
    async (cfg) => {
      const xmlDir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'res',
        'xml',
      );
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(
        path.join(xmlDir, 'network_security_config.xml'),
        NETWORK_SECURITY_CONFIG,
        'utf8',
      );
      return cfg;
    },
  ]);
}

function withHardenedManifest(config) {
  return withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);

    app.$['android:networkSecurityConfig'] = '@xml/network_security_config';
    app.$['android:usesCleartextTraffic'] = 'false';

    // Nothing in this app should be restored from a cloud backup.
    app.$['android:allowBackup'] = 'false';
    delete app.$['android:fullBackupContent'];
    delete app.$['android:dataExtractionRules'];

    return cfg;
  });
}

module.exports = function withAndroidSecurity(config) {
  return withHardenedManifest(withNetworkSecurityConfigFile(config));
};
